export const ADD_WALLET = 'ADD_WALLET';
export const REMOVE_WALLET = 'REMOVE_WALLET';
export const SET_WALLET = 'SET_WALLET';
export const TOGGLE_CURRENT_WALLET = 'TOGGLE_CURRENT_WALLET';

export const TOGGLE_CURRENT_DATE = 'TOGGLE_CURRENT_DATE';
